Javascript is single threaded, synchronous language.
This is why when you run a wait function for a specified seconds in a browser conseole, the page gets blocked for some time.


JavaScript has functions that act asynchronously.
But how can it be both synchronous and asynchronous?


Asynchronous JavaScript has this framework, blocs :

- Execution stack
- Browser APIs
- Function queue
- Event loop

To understand this pieces better, we will see an example about setTimeout() function which is one of the async js functions. 

but before that first we need to understand what is 
 `execution stack` is.  

Functions invoked by other functions get added to the call stack. When functions complete, they are removed from the stack and the frame below continues executing.

Here an example :

```js
function addOne(num) {
  return ++num
}

function getNum() {
  return addOne(10)
}

function c() {
  console.log(getNum() + getNum())
}

c()
```

when this code executed, the execution stack goes from this steps:
```
left side is stack top

[c]
[getNum, c]
[addOne,getNum,c]
Addone returns 11 to getNum
[getNum,c]
getNum retures 11 to c
[c]
c returns 11 to first getNum()
and now same thing starts for second getNum()
[getNum,c]
[addOne,getNum,c]
...
```

And this execution stack is limited by the memory as usual :)
so we can overflow it by simply infinite recursive calls:
```js
function recCall(){
    console.log("recursion..")
    return recCall()
}

recCall()
```
after so many calls, this is the error :
```
Uncaught RangeError: Maximum call stack size exceeded
```


Now to understand other JS asny framework pieces, lets dive into another example:
```js
function printOne() {
    console.log("One") 
}

function printTwo() {
    console.log("Two")
}

function printThree() {
    console.log("Three")
}

setTimeout(printOne)
setTimeout(printTwo,1000)
setTimeout(printThree,0)
```

when this code runs, the output will be this :
```
One
Three
Two
```
as you have seen, the result is not ordered (one,two,three) because setTimeout() is async function and it is what asyn means : not syncronized.

and this behaviour can be explained by this : 

![alt text](image-5.png)



## Callbacks

A callback is simply a function that is passed as an argument to another function, and then executed (called back) at a later time.

async function takes some values as parameters, do its job, connect database send req etc, then uses callback function after having return values. 

Here an example with callbacks : 

Here, User.findOne, comparePassword, jwt.sign, user.save are async functions. So they also get some callback functions.

the cons of callback is sa you can see it leads to so many nested callbacks : as known as `callback hell` :D

the promises and async/await have better syntaxtic outlook. Also callbacks need to handle errors in every callback function which also make it look messy. Promises and async/await makes it in a single function.

```js

function login(req, res, callback) {
  User.findOne({email: req.body.email}, function(err, user) {
    if (err) return callback(err)

    user.comparePassword(req.body.password, (err, isMatch) => {
      if (err) return callback(err)
      if (!isMatch) return res.status(401).send('Incorrect password')

      // add relevant data to token
      const payload = {id: user._id, email: user.email}

      jwt.sign(payload, config.secret, {}, function(err, token) {
        if (err) return callback(err)

        user.token = token
        user.save((err) => {
          if (err) return callback(err)
          res.json({token})
        })
      })
    })
  })
}

```

## Promises

Promises are almost same with callbacks but rather than passing callback function as a parameter, use .than() syntax and pass callback function to it. now when a function return its return value, if .then() is binded, this retun value will be passed to the function inside .then().


with promises you can use .then() as much as you want consequently. and for error handling you can just add 
.catch() that catches all the error raised in the upper .than()s.

here a simple example of a sample code for fething an url:

```js
const url = ''

fetch(url)
  .then(function(res) {
    return res.json()
  })
  .then(function(json) {
    return ({
      importantData: json.importantData,
    })
  })
  .then(function(data) {
    console.log(data)
  })
  .catch(function(err) {
    // handle error
  })

```



lets look at the same example with promises : 

```js
function login(req, res, callback) {
  User.findOne({email: req.body.email})
    .then(function(user) {
      return user.comparePassword(req.body.password)
    })
    .then(function(isMatch) {
      // have to throw in order to break Promise chain
      if (!isMatch) {
        res.status(401).send('Incorrect password')
        throw {earlyExit: true}
      }
      const payload = {id: user._id, email: user.email}
      return jwt.sign(payload, config.secret, {})
    })
    .then(function(token) {
      user.token = token
      return user.save()
    })
    .then(function() {
      res.json({token})
    })
    .catch(function(err) {
      if (!err.earlyExit) callback(err)
    })
}

```


## Async/Await

async/await is fairly new. it is introduced in ES2017.
Writing synchronous code using async/await feels more like writing synchronous code.

For example, since User.findOne is an async function, it will return a value in some future time. Therefore adding await make code waits for the returned value before proceeding.

```js
async function login(req, res, callback) {
    
  try {
    const user = await User.findOne({email: req.body.email})

    const isMatch = await user.comparePassword(req.body.password)

    if (!isMatch) return res.status(401).send('Incorrect password')

    const payload = {id: user._id, email: user.email}
    const token = await jwt.sign(payload, config.secret, {})

    user.token = token
    const success = await user.save()

    res.json({token})
  } catch (err) {
    callback(err)
  }
}

```

